# Generated by Django 4.0.4 on 2022-04-24 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RevokedToken',
            fields=[
                ('token', models.CharField(max_length=2024, primary_key=True, serialize=False)),
                ('exp', models.DateTimeField()),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
